import type { ProductCategory, Product } from '../types/marketplace';

export const PRODUCT_CATEGORIES: ProductCategory[] = [
  { id: 'poultry', name: 'Poultry', icon: '🐔', color: 'bg-orange-100 text-orange-800' },
  { id: 'honey', name: 'Honey', icon: '🍯', color: 'bg-yellow-100 text-yellow-800' },
  { id: 'greens', name: 'Vegetables', icon: '🥬', color: 'bg-green-100 text-green-800' },
  { id: 'eggs', name: 'Eggs', icon: '🥚', color: 'bg-amber-100 text-amber-800' },
  { id: 'fruits', name: 'Fruits', icon: '🍊', color: 'bg-red-100 text-red-800' },
  { id: 'grains', name: 'Grains', icon: '🌾', color: 'bg-yellow-100 text-yellow-700' },
  { id: 'dairy', name: 'Dairy', icon: '🥛', color: 'bg-blue-100 text-blue-800' },
  { id: 'herbs', name: 'Herbs', icon: '🌿', color: 'bg-green-100 text-green-700' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Free Range Chicken',
    description: 'Fresh, locally-raised free-range chicken. Fed with organic grain and raised in natural conditions.',
    price: 800,
    unit: 'per kg',
    category: PRODUCT_CATEGORIES[0],
    images: ['https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&h=300&fit=crop'],
    sellerId: 123,
    sellerName: 'Grace Wanjiku',
    sellerLocation: 'Kiambu County',
    inStock: true,
    stockQuantity: 25,
    harvestDate: new Date('2024-01-15'),
    freshnessDays: 3,
    rating: 4.8,
    reviewCount: 24,
    isOrganic: true,
    isFeatured: true,
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Pure Honey',
    description: 'Raw, unprocessed honey from highland beehives. Rich in natural enzymes and antioxidants.',
    price: 1200,
    unit: 'per 500g',
    category: PRODUCT_CATEGORIES[1],
    images: ['https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=300&fit=crop'],
    sellerId: 456,
    sellerName: 'John Kimani',
    sellerLocation: 'Nakuru County',
    inStock: true,
    stockQuantity: 15,
    rating: 4.9,
    reviewCount: 18,
    isOrganic: true,
    isFeatured: false,
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '3',
    name: 'Fresh Spinach',
    description: 'Crispy, fresh spinach leaves. Harvested this morning and packed with nutrients.',
    price: 50,
    unit: 'per bunch',
    category: PRODUCT_CATEGORIES[2],
    images: ['https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=300&fit=crop'],
    sellerId: 789,
    sellerName: 'Mary Nyongo',
    sellerLocation: 'Kajiado County',
    inStock: true,
    stockQuantity: 40,
    harvestDate: new Date('2024-01-18'),
    freshnessDays: 5,
    rating: 4.6,
    reviewCount: 12,
    isOrganic: true,
    isFeatured: false,
    createdAt: new Date('2024-01-18'),
  },
  {
    id: '4',
    name: 'Farm Fresh Eggs',
    description: 'Large brown eggs from free-range hens. Rich in protein and omega-3 fatty acids.',
    price: 350,
    unit: 'per tray (30 eggs)',
    category: PRODUCT_CATEGORIES[3],
    images: ['https://images.unsplash.com/photo-1518569656558-1f25e69d93d7?w=400&h=300&fit=crop'],
    sellerId: 123,
    sellerName: 'Grace Wanjiku',
    sellerLocation: 'Kiambu County',
    inStock: true,
    stockQuantity: 20,
    rating: 4.7,
    reviewCount: 28,
    isOrganic: true,
    isFeatured: true,
    createdAt: new Date('2024-01-16'),
  },
  {
    id: '5',
    name: 'Organic Tomatoes',
    description: 'Vine-ripened organic tomatoes. Perfect for cooking or fresh consumption.',
    price: 120,
    unit: 'per kg',
    category: PRODUCT_CATEGORIES[2],
    images: ['https://images.unsplash.com/photo-1546470427-227d0ac454a4?w=400&h=300&fit=crop'],
    sellerId: 456,
    sellerName: 'Peter Mwangi',
    sellerLocation: 'Meru County',
    inStock: true,
    stockQuantity: 50,
    harvestDate: new Date('2024-01-17'),
    freshnessDays: 7,
    rating: 4.5,
    reviewCount: 15,
    isOrganic: true,
    isFeatured: false,
    createdAt: new Date('2024-01-17'),
  },
];

export const COUNTIES = [
  'Nairobi', 'Kiambu', 'Nakuru', 'Kajiado', 'Meru', 'Nyeri', 'Murang\'a', 
  'Machakos', 'Kitui', 'Makueni', 'Embu', 'Tharaka Nithi', 'Isiolo', 
  'Marsabit', 'Mandera', 'Wajir', 'Garissa', 'Tana River', 'Lamu', 'Kilifi',
  'Kwale', 'Mombasa', 'Taita Taveta', 'Turkana', 'West Pokot', 'Samburu',
  'Trans Nzoia', 'Uasin Gishu', 'Elgeyo Marakwet', 'Nandi', 'Baringo',
  'Laikipia', 'Nyandarua', 'Nyamira', 'Kisii', 'Migori', 'Homa Bay',
  'Kisumu', 'Siaya', 'Busia', 'Bungoma', 'Kakamega', 'Vihiga'
];

export const DELIVERY_FEES = {
  'same-county': 100,
  'neighboring-county': 200,
  'far-county': 300,
};

export const PAYMENT_METHODS = [
  { id: 'mpesa', name: 'M-Pesa', icon: '📱', description: 'Pay with M-Pesa' },
  { id: 'card', name: 'Credit/Debit Card', icon: '💳', description: 'Pay with card' },
  { id: 'cash', name: 'Cash on Delivery', icon: '💵', description: 'Pay when you receive' },
];